### ISSUE TITLE
"ImportError: cannot import name 'AutoModelForMaskedLM' from 'transformers' (unknown location)" in case you have "transformers" directory on the same level

### ISSUE THREAD

**Issue by bysheva** [Lightning-AI/torchmetrics#1742]
### Bug description

Steps to reproduce:
1) create file.py with just one import:
`import pytorch_lightning`
2) run
`python file.py`
OK, it works
3) run
`mkdir transformers`
4) run file.py again
`python file.py`

Result: 
`root@795b76d13c29:/experiments# python file.py 
Traceback (most recent call last):
  File "file.py", line 1, in <module>
    import pytorch_lightning
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
ImportError: cannot import name 'AutoModelForMaskedLM' from 'transformers' (unknown location)`

### How to reproduce the bug

```python
touch file.py
echo "import pytorch_lightning" >> file.py
python file.py
# OK! Works good!
mkdir transformers
python file.py
# FAILED!!!
```

### Error messages and logs

root@795b76d13c29:/experiments# python file.py 
Traceback (most recent call last):
  File "file.py", line 1, in <module>
    import pytorch_lightning
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/home/user/conda/envs/research-base/lib/python3.8/site-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
ImportError: cannot import name 'AutoModelForMaskedLM' from 'transformers' (unknown location)

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): the whole module
#- PyTorch Lightning Version (e.g., 1.5.0): 1.9.4
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): "Ubuntu 20.04.5 LTS"
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): any (local and cloud)
```

</details>

**Comment by stancld** [comment]
I think we can postpone type-annotation-only imports in general. @Borda Actually, in `ruff` there are rules for checking whether the import should be in or outside `TYPE_CHECKING` block. The bad thing is I belive there's no autofix for that rule, therefore, we would need to move in all files manually. What do you think?

**Comment by SkafteNicki** [comment]
Lazy import has been implemented in torchmetrics, so closing issue.
