### ISSUE TITLE
DDP map evaluation with iou_type segm

### ISSUE THREAD

**Issue by KyanChen** [Lightning-AI/torchmetrics#1743]
When I use a single gpu, there is no error. Everything goes well.
When applying DDP, the following error occurs.

```
File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/detection/mean_ap.py", line 899, in compute
    self.lightning_module.cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/fabric/utilities/device_dtype_mixin.py", line 78, in cpu
    return super().cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 246, in cpu
    return super().cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 798, in cpu
    precisions, recalls = self._calculate(classes)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/detection/mean_ap.py", line 745, in _calculate
    return self._apply(lambda t: t.cpu())
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    ious = {
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/detection/mean_ap.py", line 746, in <dictcomp>
    module._apply(fn)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    (idx, class_id): self._compute_iou(idx, class_id, max_detections)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/detection/mean_ap.py", line 484, in _compute_iou
    module._apply(fn)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/metric.py", line 651, in _apply
    gt = [gt[i] for i in gt_label_mask]
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/detection/mean_ap.py", line 484, in <listcomp>
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/metric.py", line 651, in <listcomp>
    gt = [gt[i] for i in gt_label_mask]
IndexError: tuple index out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/search01/usr/chenkeyan/codes/lightning_framework/tools/train.py", line 57, in <module>
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 798, in <lambda>
    return self._apply(lambda t: t.cpu())
AttributeError: 'tuple' object has no attribute 'cpu'
    main()
  File "/mnt/search01/usr/chenkeyan/codes/lightning_framework/tools/train.py", line 53, in main
    runner.run(args.status, ckpt_path=args.ckpt_path)
  File "/mnt/search01/usr/chenkeyan/codes/lightning_framework/tools/../mmpl/engine/runner/pl_runner.py", line 275, in run
    return trainer_func(model=self.model, datamodule=self.datamodule, *args, **kwargs)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 68, in _call_and_handle_interrupt
    trainer._teardown()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 958, in _teardown
    self.strategy.teardown()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/strategies/ddp.py", line 430, in teardown
    super().teardown()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/strategies/parallel.py", line 125, in teardown
    super().teardown()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 475, in teardown
    self.lightning_module.cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/lightning/fabric/utilities/device_dtype_mixin.py", line 78, in cpu
    return super().cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 246, in cpu
    return super().cpu()
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 798, in cpu
    return self._apply(lambda t: t.cpu())
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/metric.py", line 651, in _apply
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torchmetrics/metric.py", line 651, in <listcomp>
    setattr(this, key, [fn(cur_v) for cur_v in current_val])
  File "/data/kyanchen/miniconda3/envs/torch1mmcv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 798, in <lambda>
    return self._apply(lambda t: t.cpu())
AttributeError: 'tuple' object has no attribute 'cpu'
```

**Comment by SkafteNicki** [comment]
Hi @KyanChen, thanks for reporting this issue.
Would it be possible for you to create a small reproduceable script that we can run to get the error?

**Comment by KyanChen** [comment]
I have found where the error is. Can the engineers of torchmetrics help the community solve the problem? That is the predictions and gts for segm IoUtype are tuple-based. Torchmetrics only allow list[tensor] based now, so it can not sync between different gpus when applying DDP mode.

**Comment by tlwzzy** [comment]
> I have found where the error is. Can the engineers of torchmetrics help the community solve the problem? That is the predictions and gts for segm IoUtype are tuple-based. Torchmetrics only allow list[tensor] based now, so it can not sync between different gpus when applying DDP mode.

maybe you can try to change your predictions from tuple-based to list-based?

**Comment by KyanChen** [comment]
The operation is in the torchmetrics lib. It can not be changed outside.

    def _get_safe_item_values(self, item: Dict[str, Any]) -> Union[Tensor, Tuple]:
        if self.iou_type == "bbox":
            boxes = _fix_empty_tensors(item["boxes"])
            if boxes.numel() > 0:
                boxes = box_convert(boxes, in_fmt=self.box_format, out_fmt="xyxy")
            return boxes
        elif self.iou_type == "segm":
            masks = []

            for i in item["masks"].cpu().numpy():
                rle = mask_utils.encode(np.asfortranarray(i))
                masks.append((tuple(rle["size"]), rle["counts"]))

            return tuple(masks)
        else:
            raise Exception(f"IOU type {self.iou_type} is not supported")

**Comment by SkafteNicki** [comment]
I am pretty sure that I can come up with a fix, but I have a hard time reproducing the error.
Would it be possible to provide an example input that causes the error?

**Comment by KyanChen** [comment]
import lightning
import torch
import torch.nn as nn
from torchmetrics.detection import MeanAveragePrecision


class ToyNet(lightning.LightningModule):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        self.metric = MeanAveragePrecision(iou_type="segm")

    def training_step(self, batch, batch_idx):
        return None

    def validation_step(self, batch, batch_idx):
        preds = []
        targets = []
        for _ in range(2):
            result = dict()
            num_preds = torch.randint(0, 10, (1,)).item()
            # result['boxes'] = torch.rand((num_preds, 4), device=self.device)
            result['scores'] = torch.rand((num_preds,), device=self.device)
            result['labels'] = torch.randint(0, 10, (num_preds,),  device=self.device)
            result['masks'] = torch.randint(0, 2, (num_preds, 10, 10),  device=self.device).bool()
            preds.append(result)
            # parse gt
            gt = dict()
            num_gt = torch.randint(0, 10, (1,)).item()
            # gt['boxes'] = torch.rand((num_gt, 4), device=self.device)
            gt['labels'] = torch.randint(0, 10, (num_gt,),  device=self.device)
            gt['masks'] = torch.randint(0, 2, (num_gt, 10, 10),  device=self.device).bool()
            targets.append(gt)
        self.metric.update(preds, targets)

    def on_validation_epoch_end(self) -> None:
        self.log_dict(self.metric.compute(), prog_bar=True)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.02)


if __name__ == '__main__':
    model = ToyNet()
    trainer = lightning.Trainer(accelerator='gpu', devices=2, max_epochs=1)
    val_dataloader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(torch.rand((10, 1)), torch.rand((10, 1))))
    trainer.validate(model, val_dataloader)

**Comment by KyanChen** [comment]
Please help me to check the following code in "torchmetrics/detection/mean_ap.py" is right?

I think list_gathered[rank] should not equal to  list_gathered[0]

```
for rank in range(1, world_size):
            if list_gathered[rank] != list_gathered[0]:
                raise ValueError(f"Rank {rank} and Rank 0 have different values for the list to gather.")
```
