### ISSUE TITLE
OSError: libcudart.so.10.2: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by shoehangxh** [Lightning-AI/torchmetrics#1951]
### To Reproduce

```
>>> import torchmetrics


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 23, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/home/pai/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 48, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/home/pai/lib/python3.9/site-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/home/pai/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pai/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/pai/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/pai/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)


OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

### Environment

torchmetrics-1.0.1
numpy (1.23.5)
lightning-utilities (0.9.0)
torch (1.12.1+cu113)

### Additional context

i don't have  'libcudart.so.10.2'  in  '/usr/local/cuda/lib64' , but any other package work well, while the 1.0.1 version is the default version via pip installation

**Comment by SkafteNicki** [comment]
Hi @shoehangxh, thanks for raising this issue.
I am very confident that this has nothing to do with `torchmetrics`, instead it is the installation of `torchaudio` that is your problem.
As you can see in the last 6 tracebacks it happens inside
```
 File "/home/pai/lib/python3.9/site-packages/torchaudio
```
directory.
Therefore try just running `import torchaudio` and you will most likely see the issue reproduced. If this is the case I would advice reopening the issue `torchaudio` github.

**Comment by shoehangxh** [comment]
> Hi @shoehangxh, thanks for raising this issue. I am very confident that this has nothing to do with `torchmetrics`, instead it is the installation of `torchaudio` that is your problem. As you can see in the last 6 tracebacks it happens inside
> 
> ```
>  File "/home/pai/lib/python3.9/site-packages/torchaudio
> ```
> 
> directory. Therefore try just running `import torchaudio` and you will most likely see the issue reproduced. If this is the case I would advice reopening the issue `torchaudio` github.

Thank you very much for your reply! i have fixed it
