### ISSUE TITLE
PeakSignalNoiseRatio RuntimeError on DDP reduction

### ISSUE THREAD

**Issue by MaugrimEP** [Lightning-AI/torchmetrics#2069]
## 🐛 Bug

I am trying to use Pytorch Lightning DDP with 2 GPUs and PeakSignalNoiseRatio Metrics.
Logging the metrics produces the error

### To Reproduce

I use the DDP on pytorch lightning with 2 GPUs and log the metrics using
```python
from torchmetrics.image import PeakSignalNoiseRatio
full_psnr_clamp = PeakSignalNoiseRatio(data_range=(-1, 1), base=10., reduction='elementwise_mean', dim=None)
...

# inside the training_step of the pytorch lightning module:
self.log(metric_name, full_psnr_clamp , on_epoch=True, on_step=True, sync_dist=True)
```

```
Traceback (most recent call last):
  File "/path/diffusion/1839322_brats2020_train_2e5/train.py", line 122, in main
    trainer.fit(
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1014, in _run_stage
    self._run_sanity_check()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1043, in _run_sanity_check
    val_loop.run()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 244, in on_run_end
    self._on_evaluation_epoch_end()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 328, in _on_evaluation_epoch_end
    trainer._logger_connector.on_epoch_end()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 188, in on_epoch_end
    metrics = self.metrics
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 229, in metrics
    return self.trainer._results.metrics(on_step)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 474, in metrics
    value = self._get_cache(result_metric, on_step)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 438, in _get_cache
    result_metric.compute()
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 278, in wrapped_func
    self._computed = compute(*args, **kwargs)
  File "/path/packages/diffusion/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 247, in compute
    return self.value.compute()
  File "/path/packages/diffusion/lib/python3.10/site-packages/torchmetrics/metric.py", line 602, in wrapped_func
    with self.sync_context(
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/pytorch-gpu-1.13.0+py3.10.8/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/path/packages/diffusion/lib/python3.10/site-packages/torchmetrics/metric.py", line 573, in sync_context
    self.sync(
  File "/path/packages/diffusion/lib/python3.10/site-packages/torchmetrics/metric.py", line 522, in sync
    self._sync_dist(dist_sync_fn, process_group=process_group)
  File "/path/packages/diffusion/lib/python3.10/site-packages/torchmetrics/metric.py", line 447, in _sync_dist
    reduced = reduction_fn(output_dict[attr]) if reduction_fn is not None else output_dict[attr]
  File "/path/packages/diffusion/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 45, in dim_zero_mean
    return torch.mean(x, dim=0)
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
```

I use torchmetrics Version: 1.1.1

I was also using other metrics as MeanAbsoluteError, StructuralSimilarityIndexMeasure, or JaccardIndex without issue, but adding this one produce an error on multi gpu

**Comment by MaugrimEP** [comment]
Ok, using `data_range=(-1., 1.)` instead of `data_range=(-1, 1)` resolve the issue I think.
Idk if it's a bug or not. kinda sus

**Comment by Borda** [comment]
> Ok, using `data_range=(-1., 1.)` instead of `data_range=(-1, 1)` resolve the issue I think. Idk if it's a bug or not. kinda sus

maybe worse to mention it in docs...
