### ISSUE TITLE
HF transformers is always imported at __init__ if available

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/torchmetrics#2242]
### Motivation

Avoid errors like
```python
Traceback (most recent call last):
  File "/workspace/lit-gpt/pretrain/tinyllama.py", line 12, in <module>
    import lightning as L
  File "/usr/local/lib/python3.10/dist-packages/lightning/__init__.py", line 20, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/__init__.py", line 27, in <module>
    from lightning.pytorch.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/__init__.py", line 14, in <module>
    from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/batch_size_finder.py", line 24, in <module>
    from lightning.pytorch.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/callbacks/callback.py", line 22, in <module>
    from lightning.pytorch.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/utilities/types.py", line 40, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 120, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/__init__.py", line 50, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/bert.py", line 23, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1343, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1355, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

Note that the `flash-attn` build issue is on my environment, but if I'm not using those text metrics (the script is not), then importing all of `transformers` is unnecessary.

My complaint is thus in this jump:

```python
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
```
from https://github.com/Lightning-AI/torchmetrics/blob/master/src/torchmetrics/functional/text/helper_embedding_metric.py#L26-L29

The imports could be made local and the typing annotations be made forward references only imported under `typing.TYPE_CHECKING`

### Pitch

`torchmetrics` should not import `transformers` unless it's going to be used.

**Comment by carmocca** [comment]
For anybody looking to contribute, here's an example PR that does the same on the lightning repository: https://github.com/Lightning-AI/lightning/pull/18551
